FROM golang:1.12.1-alpine3.9

RUN apk add --no-cache \
  bash \
  curl \
  git \
  make \
  su-exec

WORKDIR /home/$USERNAME
ENV GOPATH /home/$USERNAME/go
ENV PATH $PATH:$GOPATH/bin

COPY ./docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
